### ISSUE TITLE
Crowdin localization

### ISSUE THREAD

**Issue by MattSturgeon** [MinecraftFreecam/Freecam#145]
Some potential translators will be more familiar with tools like [Crowdin](https://crowdin.com/game-localization) and may be put off my manually working with JSON files.

Personally, I've not used Crowdin, however Minecraft and plenty of other mods (such as cloth-config) do.

My understanding is that you can setup a [free](https://crowdin.com/pricing) account which is linked to this repo. After some [configuration](https://store.crowdin.com/github) crowdin should be able to open PRs modifying the lang files with user-submitted changes.

I believe our `crowdin.yml` would be something like:

```yaml
files:
  - source: /common/src/main/resources/assets/freecam/lang/en_us.json
    translation: /common/src/main/resources/assets/freecam/lang/%language%.json
```

It may also commit directly to `main`, but I assume if that's the case you'll be able to moderate submissions on their platform instead.

Once setup, it should be referenced in the README, curseforge & modrinth.
